name: testing configration variables

on:
  workflow_dispatch:

env:
  cloud: google.cloud

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      greeting: hello
    steps:
      - name: "say hello it's karuna"
        env:
          first_name: karuna
        run: echo "$greeting $first_name is using $cloud with project ${{ vars.PROJECT_ID }}!"
